### ISSUE TITLE
Initialization Obsolete? 

### ISSUE THREAD

**Issue by JohnTendik** [bowheart/ejs-electron#7]
Hey, I'm getting this error when I try to launch electron with electron-ejs

App threw an error during load
Error: This initialization is obsolete! Please look documentation for more informations.
    at Error (native)
    at ElectronEjs (C:\Users\JTtheIT\Desktop\JT\Breaks\electron-quick-start\node_modules\electron-ejs\index.js:25:11)
    at Object.<anonymous> (C:\Users\JTtheIT\Desktop\JT\Breaks\electron-quick-start\main.js:2:42)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at loadApplicationPackage (C:\Users\JTtheIT\Desktop\JT\Breaks\electron-quick-start\node_modules\electron\dist\resources\default_app.asar\main.js:280:12)
    at Object.<anonymous> (C:\Users\JTtheIT\Desktop\JT\Breaks\electron-quick-start\node_modules\electron\dist\resources\default_app.asar\main.js:322:5)

I checked index.js, something to do with the event emitter which I do not understand. 

Anything I can do to fix this issue ?

Thanks
John

**Comment by JohnTendik** [comment]
Nvm Sorry, 

:( I installed the wrong module. GG
